"""create user auth

Revision ID: c17b2a3569ab
Revises: bd5c377bc209
Create Date: 2023-03-17 16:24:17.717332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17b2a3569ab'
down_revision = 'bd5c377bc209'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
